{"version":3,"file":"NotFoundException.js","sourceRoot":"","sources":["../../../src/api/exceptions/NotFoundException.ts"],"names":[],"mappings":";AAAA,yDAAyD;AACzD,mEAAmE;AACnE,iFAAiF;;AAEjF;;;;;;;GAOG;AAEH,wDAAqD;AAGrD,uBAA+B,SAAQ,qBAAS;IAC5C,YAAY,EAAoB;QAC5B,KAAK,CAAC,GAAG,EAAE,0BAA0B,EAAE,iBAAiB,CAAC,CAAC;IAC9D,CAAC;CACJ;AAJD,8CAIC","sourcesContent":["// Copyright (c) 2017-2018, The Particl Market developers\n// Distributed under the GPL software license, see the accompanying\n// file COPYING or https://github.com/particl/particl-market/blob/develop/LICENSE\n\n/**\n * NotFoundException\n * ----------------------------------------\n *\n * This should be used if a someone requests a\n * entity with a id, but there is no entity with this id in the\n * database, then we throw this exception.\n */\n\nimport { Exception } from '../../core/api/Exception';\n\n\nexport class NotFoundException extends Exception {\n    constructor(id?: number | string) {\n        super(404, `Entity with identifier ${id} does not exist`);\n    }\n}\n"]}